In [1]:
import numpy as np


In [21]:
board_index = np.ndarray([9, 9],dtype=[('first', 'int8'), ('second', 'int8')], )
for i in range(9):
    for j in range(9):
        board_index[i][j] = (i, j)
board_index

array([[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7),
        (0, 8)],
       [(1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7),
        (1, 8)],
       [(2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7),
        (2, 8)],
       [(3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7),
        (3, 8)],
       [(4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7),
        (4, 8)],
       [(5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7),
        (5, 8)],
       [(6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7),
        (6, 8)],
       [(7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7),
        (7, 8)],
       [(8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7),
        (8, 8)]], dtype=[('first', 'i1'), ('second', 'i1')])

In [22]:
board_index

array([[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7),
        (0, 8)],
       [(1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7),
        (1, 8)],
       [(2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7),
        (2, 8)],
       [(3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7),
        (3, 8)],
       [(4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7),
        (4, 8)],
       [(5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7),
        (5, 8)],
       [(6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7),
        (6, 8)],
       [(7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7),
        (7, 8)],
       [(8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7),
        (8, 8)]], dtype=[('first', 'i1'), ('second', 'i1')])

In [6]:
board

array([[[False, False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False,  True,  True, False],
        [False, False, False, False, False, False, False, False, False]],

       [[False, False, False, False, False, False, False, False, False],
        [ True,  True, False, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True, False, False, False]]])

In [40]:
import numpy as np

# 9 games with 9 fields
game = np.arange(1, 82).reshape((9, 9))

# 3x3x9-Array reshape
reshaped = game.reshape(3, 3, 3, 3)

# reorder axis
board_index = reshaped.transpose(0, 2, 1, 3).reshape(9, 9)
print(game)
print(reshaped)
print(board_index)


[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]]

  [[46 47 48]
   [49 50 51]
   [52 53 54]]]


 [[[55 56 57]
   [58 59 60]
   [61 62 63]]

  [[64 65 66]
   [67 68 69]
   [70 71 72]]

  [[73 74 75]
   [76 77 78]
   [79 80 81]]]]
[[ 1  2  3 10 11 12 19 20 21]
 [ 4  5  6 13 14 15 22 23 24]
 [ 7  8  9 16 17 18 25 26 27]
 [28 29 30 37 38 39 46 47 48]
 [31 32 33 40 41 42 49 50 51]
 [34 35 36 43 44 45 52 53 54]
 [55 56 57 64 65 66 73 74 75]
 [58 59 60 67 68 69 76 77 78]
 [61 62 63 70 71 72 79 80 81]]


In [41]:
# Create a mapping dictionary
mapping = {}
for i in range(9):
    for j in range(9):
        mapping[(i, j)] = (i // 3 * 3 + j // 3, i % 3 * 3 + j % 3)


In [44]:
game[mapping[(0, 4)]]

11

In [42]:
mapping

{(0, 0): (0, 0),
 (0, 1): (0, 1),
 (0, 2): (0, 2),
 (0, 3): (1, 0),
 (0, 4): (1, 1),
 (0, 5): (1, 2),
 (0, 6): (2, 0),
 (0, 7): (2, 1),
 (0, 8): (2, 2),
 (1, 0): (0, 3),
 (1, 1): (0, 4),
 (1, 2): (0, 5),
 (1, 3): (1, 3),
 (1, 4): (1, 4),
 (1, 5): (1, 5),
 (1, 6): (2, 3),
 (1, 7): (2, 4),
 (1, 8): (2, 5),
 (2, 0): (0, 6),
 (2, 1): (0, 7),
 (2, 2): (0, 8),
 (2, 3): (1, 6),
 (2, 4): (1, 7),
 (2, 5): (1, 8),
 (2, 6): (2, 6),
 (2, 7): (2, 7),
 (2, 8): (2, 8),
 (3, 0): (3, 0),
 (3, 1): (3, 1),
 (3, 2): (3, 2),
 (3, 3): (4, 0),
 (3, 4): (4, 1),
 (3, 5): (4, 2),
 (3, 6): (5, 0),
 (3, 7): (5, 1),
 (3, 8): (5, 2),
 (4, 0): (3, 3),
 (4, 1): (3, 4),
 (4, 2): (3, 5),
 (4, 3): (4, 3),
 (4, 4): (4, 4),
 (4, 5): (4, 5),
 (4, 6): (5, 3),
 (4, 7): (5, 4),
 (4, 8): (5, 5),
 (5, 0): (3, 6),
 (5, 1): (3, 7),
 (5, 2): (3, 8),
 (5, 3): (4, 6),
 (5, 4): (4, 7),
 (5, 5): (4, 8),
 (5, 6): (5, 6),
 (5, 7): (5, 7),
 (5, 8): (5, 8),
 (6, 0): (6, 0),
 (6, 1): (6, 1),
 (6, 2): (6, 2),
 (6, 3): (7, 0),
 (6, 4): (7, 1

In [36]:
for i in range(9):
    print("")
    for j in range(9):
        print(spielfeld[i, j], end="\t")


1	2	3	4	5	6	7	8	9	
10	11	12	13	14	15	16	17	18	
19	20	21	99	23	24	25	26	27	
28	29	30	31	32	33	34	35	36	
37	38	39	40	41	42	43	44	45	
46	47	48	49	50	51	52	53	54	
55	56	57	58	59	60	61	62	63	
64	65	66	67	68	69	70	71	72	
73	74	75	76	77	78	79	80	81	

In [37]:
for i in range(9):
    print("")
    for j in range(9):
        print(final_reshape[i, j], end="\t")


1	2	3	10	11	12	19	20	21	
4	5	6	13	14	15	22	23	24	
7	8	9	16	17	18	25	26	27	
28	29	30	37	38	39	46	47	48	
31	32	33	40	41	42	49	50	51	
34	35	36	43	44	45	52	53	54	
55	56	57	64	65	66	73	74	75	
58	59	60	67	68	69	76	77	78	
61	62	63	70	71	72	79	80	81	

In [34]:
spielfeld[2, 3] = 99

In [347]:
class Game:
    WINNING_COMBINATIONS = np.array([
        # rows
        [True, True, True, False, False, False, False, False, False],
        [False, False, False, True, True, True, False, False, False],
        [False, False, False, False, False, False, True, True, True],
        # columns
        [True, False, False, True, False, False, True, False, False],
        [False, True, False, False, True, False, False, True, False],
        [False, False, True, False, False, True, False, False, True],
        # diagonals
        [False, False, True, False, True, False, True, False, False],
        [True, False, False, False, True, False, False, False, True],
    ])


    class _Player:
        def __init__(self, color):
            self.history = []
            self.board = np.zeros((9,9), dtype=bool)
            self.wins = np.zeros((9,), dtype=bool)
            self.color = color


    def __init__(self):
        self.white = Game._Player("white") # white is O and starts
        self.black = Game._Player("black") # black is X
    

    @property
    def current_player(self):
        if len(self.white.history) == len(self.black.history):
            return self.white
        return self.black
    

    @property
    def last_move(self):
        if not self.white.history and not self.black.history:
            return None
        if len(self.white.history) == len(self.black.history):
            return self.black.history[-1]
        else:
            return self.white.history[-1]

    
    @property
    def blocked_fields(self):
        if self.last_move is None:
            return np.zeros((9, 9), dtype=bool)

        blocked_fields = self.white.board | self.black.board
        finished_games = (self.white.wins | self.black.wins)[:, np.newaxis] * np.ones((9, 9), dtype=bool)
        blocked_fields = blocked_fields | finished_games
        
        # if a whole game is blocked, return the rest of the games as free
        if all(blocked_fields[self.last_move[1]]):
            return blocked_fields
        
        blocked_games = np.ones((9,9), dtype=bool)
        blocked_games[self.last_move[1]] = np.zeros((9,), dtype=bool)

        blocked_fields = blocked_fields | blocked_games
        return blocked_fields



    def check_valid_move(self, game_idx, field_idx):
        return not self.blocked_fields[game_idx, field_idx]


    def check_win(board):
        '''
        Get a 3x3 board and checks if there is a winning combination hit.
        '''
        win_combs = Game.WINNING_COMBINATIONS # get all combinations to win a game
        win_mask = win_combs & board # get just the moves that hits a winning combination
        win_list = np.all(win_mask == win_combs, axis=1) # check if all hits for a winning combination were made
        return np.any(win_list) # determine if a winning combination was hit
    

    def play(self, game_idx, field_idx):
        if not self.check_valid_move(game_idx, field_idx):
            raise ValueError(f"You tried to play on a blocked field ({game_idx}, {field_idx})!")
        
        current_player = self.current_player
        current_player.history.append((game_idx, field_idx))
        current_player.board[game_idx, field_idx] = True

        # if self.black.wins[game_idx] == True or self.white.wins[game_idx] == True:
        #     return None

        if Game.check_win(current_player.board[game_idx]):
            current_player.wins[game_idx] = True
            print(f"{current_player.color} wins local game {game_idx}")
            if Game.check_win(current_player.wins):
                print(f"{current_player.color} wins global game") # TODO: what do we make with wins?


    def _reshape_board(board):
        # 3x3x9-Array reshape
        reshaped = board.reshape(3, 3, 3, 3)

        # reorder axis
        return reshaped.transpose(0, 2, 1, 3).reshape(9, 9)


    def __repr__(self):
        game = np.zeros((9, 9))
        game[self.black.board] = -1
        game[self.white.board] = 1
        reshaped_board = Game._reshape_board(game)

        blocked_fields = Game._reshape_board(self.blocked_fields)
        
        rows = []
        for i in range(9):

            row = []
            for j in range(9):
                if j in (3, 6):
                    row.append(" ")
                match int(reshaped_board[i, j]):
                    case 1:
                        row.append("X")
                    case -1:
                        row.append("O")
                    case 0:
                        if blocked_fields[i, j]:
                            row.append("·")
                        else:
                            row.append("•")
            if i in (3, 6):
                rows.append("\n")
            rows.append("  ".join(row) + "\n")

        repr = "".join(rows)

        # reorder axis
        return repr

In [348]:
game_1 = Game()
game_1.play(4, 4)
game_1.play(4, 6)
game_1.play(6, 7)
game_1.last_move
#game_1.get_blocked_fields()
game_1.play(7, 4)
game_1.play(4, 1)
game_1.play(1, 4)
game_1.play(4, 7)
game_1.play(7, 0)
game_1.play(0, 4)
game_1.play(7, 8)
game_1.play(8, 0)
game_1.play(0, 0)
game_1.play(0, 6)
game_1.play(6, 4)
game_1.play(0, 8)
game_1.play(8, 8)
game_1.play(8, 2)
game_1.play(2, 6)
game_1.play(6, 6)
game_1.play(6, 8)
game_1.play(8, 1)
game_1.play(1, 2)
game_1.play(2, 4)
# game_1.play(3, 4)
# game_1.play(0, 7)



print(game_1.last_move)
print(game_1.current_player.color)
game_1

white wins local game 4
black wins local game 7
white wins local game 8
(2, 4)
black


O  •  •     •  •  O     •  •  •
•  X  •     •  O  •     •  X  •
X  •  X     •  •  •     O  •  •

•  •  •     ·  X  ·     •  •  •
•  •  •     ·  X  ·     •  •  •
•  •  •     O  X  ·     •  •  •

•  •  •     O  ·  ·     X  X  X
•  O  •     ·  O  ·     ·  ·  ·
X  X  O     ·  ·  O     ·  ·  O